# Generated by Django 4.2 on 2023-05-23 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('deprecated', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='member')),
                ('projects', models.ManyToManyField(blank=True, related_name='projects', to='projects.project', verbose_name='projects')),
                ('teamleaders', models.ManyToManyField(blank=True, related_name='teamleaders', to=settings.AUTH_USER_MODEL, verbose_name='teamleaders')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ('name',),
            },
        ),
    ]
