# Generated by Django 4.2 on 2023-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('projectcategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='description')),
                ('project', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='categories.category', verbose_name='categories')),
                ('project_categories', models.ManyToManyField(blank=True, related_name='categories_project', to='projectcategories.projectcategory', verbose_name='categories_project')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projects',
                'ordering': ('name',),
            },
        ),
    ]
