# Generated by Django 4.2 on 2023-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customusers', '0001_initial'),
        ('projectcategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, to='projectcategories.projectcategory'),
        ),
    ]
