# Generated by Django 4.2 on 2023-05-23 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('days', '0002_initial'),
        ('teams', '0001_initial'),
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2023)),
                ('month', models.PositiveIntegerField(default=1)),
                ('deprecated', models.BooleanField(default=False)),
                ('holidays', models.ManyToManyField(blank=True, to='holidays.holiday', verbose_name='holidays')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name': 'monthly report',
                'verbose_name_plural': 'monthly reports',
                'ordering': ('year', 'month'),
            },
        ),
        migrations.CreateModel(
            name='UserMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2023)),
                ('month', models.PositiveIntegerField(default=1)),
                ('days', models.ManyToManyField(blank=True, to='days.day', verbose_name='days')),
                ('refer_mr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.monthlyreport')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user monthly report',
                'verbose_name_plural': 'user monthly reports',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='umrs',
            field=models.ManyToManyField(blank=True, to='reports.usermonthlyreport', verbose_name='UserMonthlyReports'),
        ),
    ]
