# Generated by Django 4.2 on 2023-05-23 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('days', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2023)),
                ('week', models.PositiveIntegerField(default=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('days_max', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'weekdate',
                'verbose_name_plural': 'weekdates',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_max', models.PositiveIntegerField(default=5)),
                ('lock', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('days', models.ManyToManyField(blank=True, to='days.day', verbose_name='days')),
                ('refer_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_refer_team', to='teams.team', verbose_name='team')),
                ('refer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_week_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('weekdate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekdate', to='weeks.weekdate', verbose_name='week')),
            ],
            options={
                'verbose_name': 'week',
                'verbose_name_plural': 'weeks',
                'ordering': ('pk',),
            },
        ),
    ]
