# Generated by Django 4.2 on 2023-05-23 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('type', models.CharField(choices=[('default', 'default'), ('weekend', 'weekend'), ('holiday', 'holiday')], default='default', max_length=10)),
                ('refer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_day_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
                'ordering': ('pk',),
            },
        ),
    ]
