# Generated by Django 4.2 on 2023-05-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weeks', '0001_initial'),
        ('days', '0001_initial'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='refer_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_day_week', to='weeks.week', verbose_name='Week'),
        ),
        migrations.AddField(
            model_name='day',
            name='slots',
            field=models.ManyToManyField(blank=True, to='slots.slot', verbose_name='slots'),
        ),
    ]
